// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLWzIVOGf-Nr-czEE99ItbFWW8iS-LqTM',
    appId: '1:599497594499:web:f471486e795e03cf5cedb6',
    messagingSenderId: '599497594499',
    projectId: 'doanltdd-a9921',
    authDomain: 'doanltdd-a9921.firebaseapp.com',
    storageBucket: 'doanltdd-a9921.firebasestorage.app',
    measurementId: 'G-5VYEWH49VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCunugI6V88qhZOZjyKTwVYIM_64zNbAVU',
    appId: '1:599497594499:android:fe60f4bbc291849f5cedb6',
    messagingSenderId: '599497594499',
    projectId: 'doanltdd-a9921',
    storageBucket: 'doanltdd-a9921.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzOa9iAo7PoumkhOjT2U-TrrLwJ6drITU',
    appId: '1:599497594499:ios:87f940e93166879c5cedb6',
    messagingSenderId: '599497594499',
    projectId: 'doanltdd-a9921',
    storageBucket: 'doanltdd-a9921.firebasestorage.app',
    iosBundleId: 'com.example.doanltdd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzOa9iAo7PoumkhOjT2U-TrrLwJ6drITU',
    appId: '1:599497594499:ios:87f940e93166879c5cedb6',
    messagingSenderId: '599497594499',
    projectId: 'doanltdd-a9921',
    storageBucket: 'doanltdd-a9921.firebasestorage.app',
    iosBundleId: 'com.example.doanltdd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLWzIVOGf-Nr-czEE99ItbFWW8iS-LqTM',
    appId: '1:599497594499:web:c8edc8d2b486a4085cedb6',
    messagingSenderId: '599497594499',
    projectId: 'doanltdd-a9921',
    authDomain: 'doanltdd-a9921.firebaseapp.com',
    storageBucket: 'doanltdd-a9921.firebasestorage.app',
    measurementId: 'G-24D48K4M7X',
  );
}
